#ifndef COMPILADORES_DEFINICIONES_H
#define COMPILADORES_DEFINICIONES_H

#define SIZE_BLOCK 255
#define INIT_SIZE_HASH_TABLE 50
#define FILL_LIMIT_HASH_TABLE 0.75

//DelimiterKeywords
#define IMPORT 300
#define RETURN 301
#define CAST 302
#define WHILE 303
#define FOREACH 304
#define DOUBLE 306
#define INT 307
#define EXPONENTIAL 308
#define BINARY 309
#define VOID   310
//DelimiterKeywords

//Content of identifiers
#define NUMBER_INT 500
#define NUMBER_DOUBLE 501
#define NUMBER_BINARY 502
#define NUMBER_EXPONENTIAL 503
#define STRING 504
#define IDENTIFIER 505

//Operadores
#define LEFT_BRACKET   600
#define RIGHT_BRACKET   601
#define SQUARE_LEFT_BRACKET   602
#define SQUARE_RIGHT_BRACKET   603
#define CURLY_LEFT_BRACKET      604
#define CURLY_RIGHT_BRACKET     605
#define OPERATION_EQUALS 610
#define OPERATION_ASSIGN 611



//Comments & strings
#define COMMENT_MULTIPLE 801
#define COMMENT_HIERARCHIC 803
#define LINE_COMMENT    805
#define DOCUMENT_LINE_COMMENT    806
#define DOCUMENT_MULTIPLE_COMMENT    806
//Errors
#define BAD_FORMATED_NUMBER 900
#define BAD_FORMATED_DOUBLE 902
#define BAD_FORMATED_EXP 903
#define BAD_FORMATED_BINARY 903
#define COMMENT_DOES_NOT_END 904
#define STRING_DOES_NOT_END 905
#define STRING_JUMP_LINE 906
#define UNEXPECTED_CHAR 907

#define END_OF_FILE -100
#endif //COMPILADORES_DEFINICIONES_H
